// Campuses
export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES';
export const RECEIVE_CAMPUS = 'RECEIVE_CAMPUS';
export const DELETE_CAMPUS = 'DELETE_CAMPUS'
export const ADD_CAMPUS = 'ADD_CAMPUS'

// Student
export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS';
export const RECEIVE_STUDENT = 'RECEIVE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const ADD_STUDENT = 'ADD_STUDENT'
